# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Esta migração inicial está vazia porque estamos usando a tabela auth_user existente
        # do Django. Nossa customização usa a mesma tabela (db_table = 'auth_user')
    ]
